config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        registrations: 'users/registrations'
    }
    devise_scope :user do
        get 'login', to: 'devise/sessions#new'
        post 'login', to: 'devise/sessions#create'
        delete 'logout', to: 'devise/sessions#destroy'
    end

    root "posts#index"
    resources :users, only: %i[show]
    resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    scope :recent, -> { order(created_at: :desc) }

    DRAFT_OFF = 0
    DRAFT_ON = 1
    PUBLIC_OFF = 0
    PUBLIC_ON = 1
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    has_many :posts, dependent: :destroy

    validates :name, presence: true
    validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def after_sign_in_path_for(resource)
        root_path
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: %i[index]
    before_action :correct_user, only: %i[destroy]

    def index
        @posts = Post.recent.paginate(page: params[:page], per_page: 5)
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:success] = "投稿しました"
            redirect_to root_url
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            flash[:success] = "更新しました"
            redirect_to @post
        else
            redirect_to :edit
        end

    end

    def destroy
        @post.destroy
        flash[:success] = "削除しました"
        redirect_to root_url, status: 303
    end

    private
    def post_params
        params.require(:post).permit(:title, :body)
    end

    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        redirect_to root_url if @post.nil?
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
    #
    def after_update_path_for(resource)
        user_path(id: current_user.id)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user && user == current_user
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Qiita Demo" , root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home" , root_path %>
        </li>
        <% if user_signed_in?	%>
          <li>
            <%= link_to "Log out" , logout_path, data: { turbo_method: :delete } %>
          </li>
          <li>
            <%= link_to "投稿する", new_post_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in" , login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" 　class="card">

  <div class="card-header">
    <div><%= post.user.name %> <span><%= l post.created_at, format: :ymd %></span></div>
    <div></div>

  </div>
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= post.body %></p>
    <%= link_to "Go Post Detail", post, class: "btn btn-primary" %>
  </div>

</div>

app/views/posts/_post_form.html.erb
<%= form_with(model: @post, local: true, data: { turbo: false }) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "タイトル" %>
  </div>
  <div class="field">
    <%= f.text_area :body, placeholder: "技術記事を書こう" %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<!--  <span class="image">-->
    <%#= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
<!--  </span>-->
<% end %>

<!--<script type="text/javascript">-->
<!--    $("#micropost_image").bind("change", function() {-->
<!--        const size_in_megabytes = this.files[0].size/1024/1024;-->
<!--        if (size_in_megabytes > 5) {-->
<!--            alert("Maximum file size is 5MB. Please choose a smaller file.");-->
<!--            $("#micropost_image").val("");-->
<!--        }-->
<!--    });-->
<!--</script>-->

app/views/posts/edit.html.erb
<h1>更新</h1>
<%= render 'posts/post_form' %>

app/views/posts/index.html.erb
<h3>新着投稿</h3>

<%= render @posts %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>新規作成</h1>
<%= render 'posts/post_form' %>

app/views/posts/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="post_info">
      <h1>
        <%= @post.title %>
      </h1>
    </section>
    <section class="body">
      <%= @post.body %>
    </section>
  </aside>

  <% if current_user?(@post.user) %>
    <%= link_to '更新', edit_post_path %>
    <%= link_to '削除', post_path, data: { turbo_method: :delete, turbo_confirm: "削除してもいいですか？" } %>
  <% end %>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>